"""Add new column

Revision ID: e435ffae50be
Revises: d742473bf5b6
Create Date: 2024-05-18 21:29:17.504828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e435ffae50be'
down_revision: Union[str, None] = 'd742473bf5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('download_count', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('items', 'download_count')
